# build.yaml
#
# Copyright (c) 2019-2020 VMware, Inc.
#
# SPDX-License-Identifier: https://spdx.org/licenses/MIT.html
#

platform: linux

image_resource:
  type: docker-image
  source:
    repository: ((taskimage))
    tag: ((taskimagetag))

inputs:
  - name: sources

outputs:
  - name: build

run:
  path: sources/ci/scripts/build.sh
