# permissions to do edit kwites.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kwite-editor-role
rules:
- apiGroups:
  - web.kwite.site
  resources:
  - kwites
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - web.kwite.site
  resources:
  - kwites/status
  verbs:
  - get
  - patch
  - update
