# permissions to do viewer kwites.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kwite-viewer-role
rules:
- apiGroups:
  - web.kwite.site
  resources:
  - kwites
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - web.kwite.site
  resources:
  - kwites/status
  verbs:
  - get
