apiVersion: web.kwite.site/v1beta1
kind: Kwite
metadata:
  name: kwite-1
spec:
  url: "/kwite"
  port: 8080
  image: "registry.hub.docker.com/tdhite/kwite:latest"
  targetcpu: 50
  minreplicas: 1
  maxreplicas: 10
  ready: "OK!"
  alive: "OK!"
  template: |
    This is a sample template that when executed x was {{ .x }}.

    {{ httpGet "http://kwite-2.kwiteop-system/kwite" "" "Accept" "text/plain" }}

    What's next is the result of string computations via the strCompare function:

    {{ $s1 := "aaa" -}} {{- $s2 := "bbb" -}} {{- $comp := strCompare $s1 $s2 -}}
    {{ $s1 }} is {{ if ($comp) lt 0 -}} less {{ else -}} greater {{ end -}} than {{ $s2 }}.
    {{ $s2 }} is {{ if ($comp) gt 0 -}} greater {{ else -}} less {{ end -}} than {{ $s1 }}.


    Here is the output from the use of strNewReplacer and subsequent Replace functions:

    {{ $r := strNewReplacer "<" "&lt;" ">" "&gt;" }}
    {{- $r.Replace "This is some italicized <i>HTML</i>!" }}


    The arccos of sin(Pi) is {{ Acos (Sin Pi) }} radians.

    And the rest is supposedly the smallest web site in the world (guimp.com):

    {{ httpGet "http://www.guimp.com" "{\"x\": 2}" "Accept" "text/plain" "Content-type" "application/json" }}
